name: dashbook
description: A showcase/sandbox library to help you build isolated widgets in Flutter
version: 0.0.11
homepage: https://github.com/erickzanardo/dashbook

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^0.3.4
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
